<a href="https://colab.research.google.com/github/singhggithub/machine-learning-tools-and-technique/blob/master/Copy_of_Python_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### NumPy is a module for Python. The name is an acronym for  "Numerical Python". It is pronounced NUM-py

## It is an extension module for Python, mostly written in C. 

### This makes sure that the precompiled mathematical and numerical functions and functionalities of Numpy guarantee great execution speed.

### SciPy (Scientific Python) is often mentioned in the same breath with NumPy. SciPy needs Numpy, as it is based on the data structures of Numpy 

### Both NumPy and SciPy are not part of a basic Python installation. They have to be installed after the Python installation. NumPy has to be installed before installing SciPy.
pip install numpy scipy

# 1.Import NumPy

In [18]:
import numpy

In [19]:
%%time
### Create a numpy array
arr=numpy.array([1,2,3,5,4,6])
print(arr)

[1 2 3 5 4 6]
CPU times: user 339 µs, sys: 0 ns, total: 339 µs
Wall time: 307 µs


# 2.NumPy as np

### NumPy is usually imported under the np alias.alias: In Python alias are an alternate name for referring to the same thing.

Create an alias with the as keyword while importing:

In [20]:
### Create a numpy array
import numpy as np
arr1=np.array((1,2,3))
print(arr1)

[1 2 3]


# 3.Checking NumPy Version

In [21]:
print(np.__version__)  # __version__

1.21.6


In [22]:
type(arr)
type(arr1)

numpy.ndarray

In [23]:
#create a 2-dimensional array of size 2 x 3, composed of integer elements
#homogenious elements-- of same data type
arr2=np.array([[1,2,3],[4,5,6]])   #([[],[]])
print(type(arr2))
print(arr2)
print(arr2.shape)
print(arr2.dtype)

<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]]
(2, 3)
int64


In [24]:
### create a 3x6 array 
arr3=np.array([[1,2,3,4,5,6],[1,2,3,4,5,6],[1,2,3,4,5,6]])
print(arr3)

[[1 2 3 4 5 6]
 [1 2 3 4 5 6]
 [1 2 3 4 5 6]]


# 4.Time Comparison between Python Lists and Numpy Arrays

In [25]:
#Return evenly spaced values within a given interval. Values are generated within the half-open interval [start, stop)
my_arr = np.arange(1000000)
my_list = list(range(1000000))
print(my_arr)

[     0      1      2 ... 999997 999998 999999]


In [26]:
print(my_list)

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



In [27]:
%time for _ in range(10): my_arr2 = my_arr * 2
print(my_arr2)

CPU times: user 11.3 ms, sys: 1.85 ms, total: 13.1 ms
Wall time: 12.8 ms
[      0       2       4 ... 1999994 1999996 1999998]


In [28]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

CPU times: user 525 ms, sys: 89.7 ms, total: 615 ms
Wall time: 621 ms


# 5.Dimensions in Arrays

# 0-D Arrays

Create a 0-D array with value 42

In [29]:
arr4=np.array(42)
print(arr4)

42


# 1-D Arrays

In [30]:
arr5=np.array([1,2,34,5])
print(arr5)

[ 1  2 34  5]


# 2-D Arrays

In [31]:
arr6=np.array([[1,2,3],[4,5,6]])
print(arr6)

[[1 2 3]
 [4 5 6]]


# 3-D arrays

In [32]:
import numpy as np
y=np.array([[[1,2,3],[4,5,6]],[[1,1,1],[2,3,2]]])
print(y)

[[[1 2 3]
  [4 5 6]]

 [[1 1 1]
  [2 3 2]]]


# 5.Check Number of Dimensions?

Check how many dimensions the arrays have:

In [33]:
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [34]:
import numpy as np
a = np.array([1,2,3,4,5,6])
a = a.reshape(3,2)
a
a = a.reshape(2,-1) ## -1--> unknown dimension
a
a = a.ravel()
a

array([1, 2, 3, 4, 5, 6])

# 6.linspace

In [35]:
#numpy.linspace(start, stop,num = 50, endpoint = True, retstep = False, dtype = None)
-> start  : [optional] start of interval range. By default start = 0
-> stop   : end of interval range
-> restep : If True, return (samples, step). By deflut restep = False
-> num    : [int, optional] No. of samples to generate
-> dtype  : type of output array

SyntaxError: ignored

In [ ]:
import numpy as np
# 50 values between 1 and 10:
print(np.linspace(1,10,num = 50))

In [ ]:
# 7 values between 1 and 10:
print(np.linspace(1,10,num = 7,endpoint = False))

In [36]:
A = np.array([
[11, 12, 13, 14, 15],
[21, 22, 23, 24, 25],
[31, 32, 33, 34, 35],
[41, 42, 43, 44, 45],
[51, 52, 53, 54, 55]])
print(A)


[[11 12 13 14 15]
 [21 22 23 24 25]
 [31 32 33 34 35]
 [41 42 43 44 45]
 [51 52 53 54 55]]


In [37]:
print(A[1:3, 2:])  #(row, column)### 3 not included

[[23 24 25]
 [33 34 35]]


![image.png](attachment:image.png)

In [ ]:
# print the above representation
print(A[:3, 2:])

In [ ]:
print(A[3:, :])

![image.png](attachment:image.png)

In [ ]:
print(A[:, :2])

In [38]:
print(A[:, 2:4])

[[13 14]
 [23 24]
 [33 34]
 [43 44]
 [53 54]]


In [ ]:
y= np.arange(28)
X = np.arange(28).reshape(4,7)
print(X)
print(y)

In [ ]:
print(X[::2, ::3])

![image.png](attachment:image.png)

In [ ]:
print(A[:, :3:2])

In [ ]:
print(A[:, ::2])

# Creating Arrays with Ones, Zeros and Empty

In [ ]:
# 2x3 array of all 1s
z= np.ones((2,3))
print(z)

In [ ]:
z1= np.ones((2,3),dtype=int)
print(z1)

In [ ]:
z2= np.zeros((2,3),dtype=int)
print(z2)

In [ ]:
z3= np.empty((2,3))
print(z3)

# Copying Arrays

In [ ]:
Y=z2

In [ ]:
Y

In [ ]:
Z[1,1]=3


In [ ]:
Z

In [ ]:
Y

# numpy.copy()

In [ ]:
A = np.array([
[11, 12, 13, 14, 15],
[21, 22, 23, 24, 25],
[31, 32, 33, 34, 35],
[41, 42, 43, 44, 45],
[51, 52, 53, 54, 55]])
print(A)

In [ ]:
e=A
print(e)

In [ ]:
print(e)

In [ ]:
w=A.copy()

In [ ]:
print(w)

In [ ]:
A[0,0]=2

In [ ]:
print(w)

# The identity Matrix

In [ ]:
import numpy as np
np.identity(4)

In [ ]:
np.identity(4, dtype=int)

In [ ]:
import numpy
numpy.eye(3, dtype=int)

In [ ]:
np.eye(3,4,-1, dtype=int)

# Graphical Representation of the Values

In [ ]:
cvalues = [20.1, 20.8, 21.9, 22.5, 22.7, 22.3, 21.8, 21.2, 20.9, 20.1]

In [ ]:
C = np.array(cvalues)
print(C)

In [ ]:
import matplotlib.pyplot as ks
ks.plot(C)

In [ ]:
# diag` extracts a diagonal or constructs a diagonal array.
d=([4,5,6])
np.diag(d)

In [ ]:
n = np.arange(0, 30, 2) # start at 0 count up by 2, stop before 30
print(n)
n = n.reshape(5, 3) # reshape array to be 3x5
print(n)

In [ ]:
# Create an array using repeating list
np.array([1, 2, 3] * 3)

In [ ]:
np.tile([1, 2, 3], 3)

In [ ]:
np.repeat([1, 2, 3], 3)

# Operations
Use +, -, *, / and ** to perform element wise addition, subtraction, multiplication, division and power.

In [ ]:
mylist = [1, 2, 3]
x = np.array(mylist)
print(x)
y = np.array([4, 5, 6])
print(y)

In [ ]:
print(x + y) # elementwise addition     [1 2 3] + [4 5 6] = [5  7  9]
print(x - y) # elementwise subtraction  [1 2 3] - [4 5 6] = [-3 -3 -3]
x1 = np.array([[1,2,3],[3,4,5]])
y1 = np.array([[1,1,1], [2,2,2]])
print(x1+y1)

In [ ]:
print(x * y) # elementwise multiplication  [1 2 3] * [4 5 6] = [4  10  18]
print(x / y) # elementwise divison    [1 2 3] / [4 5 6] = [0.25  0.4  0.5]

In [ ]:
print(x**2) # elementwise power  [1 2 3] ^2 =  [1 4 9]

<br>
**Dot Product:**  

$ \begin{bmatrix}x_1 \ x_2 \ x_3\end{bmatrix}
\cdot
\begin{bmatrix}y_1 \\ y_2 \\ y_3\end{bmatrix}
= x_1 y_1 + x_2 y_2 + x_3 y_3$

In [ ]:
x.dot(y) # dot product  1*4 + 2*5 + 3*6

In [ ]:
x1=np.array([[1,2,3],[4,5,6],[7,8,9]])
y1=np.array([[1,1,1],[2,2,2],[3,3,3]])

np.dot(x1,y1)

In [ ]:
a= np.array([[1,2],[4,5],[7,8]])
b=np.array([[1,1,1],[1,1,1]])
print(a)
print(b)
print(a.dot(b))

In [ ]:
# Use `.T` to get the transpose.
z = np.array([y, y**2])
print(z)
print(z.T)
z.transpose()

In [ ]:
# Use `.dtype` to see the data type of the elements in the array.
z.dtype

In [ ]:
a = np.array([-4, -2, 1, 3, 5,7,9,11,-4,1,4,1])

In [ ]:
a.sum()

In [ ]:
print(a.max())
print(a.argmax())    # index of max

In [ ]:
print(a.min())
print(a.argmin())           # index of min

In [ ]:
a.mean()

In [ ]:
a.std()

In [ ]:
a.var()

In [ ]:
from scipy import stats
mode = stats. mode(a)
mode

In [ ]:
from scipy.stats import skew 
import numpy as np  
  
# random values based on a normal distribution 
x = np.random.normal(0, 2, 10000) 
y = np.array([1, 2, 3, 4, 1000])
z = np.array([1, 899, 900, 910, 1000])
w = np.array([1, 2, 3, 4,5])              # uniform distribution
print ("X : \n", x) 
  
print('\nSkewness for data : ', skew(x))
print('\nSkewness for data : ', skew(y))
print('\nSkewness for data : ', skew(z))
print('\nSkewness for data : ', skew(w))

In [ ]:
import numpy
my_array = []
a = int(input("Size of array:"))
for i in range(a):
    my_array.append(int(input("Element:")))
my_array = numpy.array(my_array)
print(my_array)

In [ ]:
#Take matrix size as input
n=int(input("Enter the matrix size"))

import numpy as np

#initialise nxn matrix with zeroes
mat=np.zeros((n,n))
print(mat)

#input each row at a time,with each element separated by a space
for i in range(n):
   mat[i]=input().split(" ")
print(mat)

In [ ]:
Randomly generate the marks of the 80 students in the range of 40 to 95. Write a NumPy 
program to compute the 70 percentile for all elements in a given array. (Hint: use 
np.random.randint (start, stop, no_of_items) for list generation) (Hint: Use np.percentile)

In [ ]:
import numpy as np
arr=np.random.randint (40, 96, 80)
print(arr)